version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=score-server
      - POSTGRES_PASS=score-server
      - POSTGRES_DB=scores
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=score-server
      - POSTGRES_PASSWORD=score-server
      - POSTGRES_DB=scores
