services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=score-server
      - POSTGRES_PASS=score-server
      - POSTGRES_DB=scores
      - SCORE_DEFAULT_GAME=default_game
      - SCORE_DEFAULT_GAME_NAME=Default Game
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      - POSTGRES_USER=score-server
      - POSTGRES_PASSWORD=score-server
      - POSTGRES_DB=scores
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
