services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - SCORE_DEFAULT_GAME_ID=${SCORE_DEFAULT_GAME_ID}
      - SCORE_DEFAULT_GAME_NAME=${SCORE_DEFAULT_GAME_NAME}
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
